platform :ios, '10.0'

use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ours-curiosity/CTSpecs'

target 'CTStorage_Example' do
  pod 'CTStorage', :path => '../'

end
